### ISSUE TITLE
Tracking integration for Document QA

### ISSUE THREAD

**Issue by osanseviero** [huggingface/hub-docs#299]
## Tracking integration of task - **name of task**

Note that you're not expected to do all of the following steps. This PR helps track all the steps required to get a new task fully supported in the Hub 🔥

- [ ] Integration with Inference API. Select at least one of the following:
  - [x] Added a `transformers` `pipeline`
  - [ ] Added to Community Inference API for 3rd party library
  - [ ] Added to Community Inference API for generic
- [x] Added basic UI elements (icon, order specification, etc)
- [x] Added a widget

Integration guide: https://hf.co/docs/hub/models-tasks

**Comment by ankrgyl** [comment]
Happy to take this task.

**Comment by ankrgyl** [comment]
@osanseviero I started working on the widget, and got an error that there is no hosted inference API for document-question-answering available yet. Is that something that has to be deployed (https://github.com/huggingface/transformers/commit/2ef774211733f0acf8d3415f9284c49ef219e991 is the commit that adds it).

**Comment by ankrgyl** [comment]
Oh I just saw @NielsRogge's comment on https://github.com/huggingface/transformers/issues/18926. Looks like @Narsil needs to enable the inference API.

**Comment by osanseviero** [comment]
Yes, we'll need to wait for Narsil :)

**Comment by osanseviero** [comment]
This is now deployed, so closing as it's fixed!
