### ISSUE TITLE
Tracking integration for text-nearest

### ISSUE THREAD

**Issue by osanseviero** [huggingface/hub-docs#35]
## Tracking integration of task - text-nearest

Naming is tentative 

Note that you're not expected to do all of the following steps. This PR helps track all the steps required to get a new task fully supported in the Hub 🔥

- [x] Integration with Inference API. Select at least one of the following:
  - [ ] Added a `transformers` `pipeline`
  - [x] Added to Community Inference API for 3rd party library
  - [ ] Added to Community Inference API for generic
- [x] Added basic UI elements (icon, order specification, etc)
- [x] Added a widget

Integration guide: https://hf.co/docs/hub/adding-a-task

We can do this with gensim or fasttext models for example for obtaining closest words with nearest neighbors. Example repo: https://huggingface.co/Hellisotherpeople/debate2vec

CC @mishig25 in case you would like to help with the widget, this is pretty much the same as the `text-classification` widget

**Comment by osanseviero** [comment]
GIving it's been 2 years and we've had no further requests for this nor more models, I will close it.
