### ISSUE TITLE
Tracking integration for video classification

### ISSUE THREAD

**Issue by nateraw** [huggingface/hub-docs#36]
## Tracking integration of task - **video-classification**

Note that you're not expected to do all of the following steps. This PR helps track all the steps required to get a new task fully supported in the Hub 🔥

- [x] Integration with Inference API. Select at least one of the following:
  - [x] Added a `transformers` `pipeline`
  - [ ] Added to Community Inference API for 3rd party library
  - [ ] Added to Community Inference API for generic
- [x] Added basic UI elements (icon, order specification, etc)
- [ ] Added a widget

Integration guide: https://hf.co/docs/hub/adding-a-task

**Comment by osanseviero** [comment]
Pipeline is supported, but widget isn't. Closing for now as the widget has not been requested much cc @mishig25
