### ISSUE TITLE
Tracking widget inference run `onLoad`

### ISSUE THREAD

**Issue by mishig25** [huggingface/hub-docs#368]
## Tracking widget inference run `onLoad`

Expected behaviour: when a user visits a model page (for example [this page](https://huggingface.co/facebook/detr-resnet-50))
, widget should run immediately if:
* there is an the modelcard has [example widget input](https://huggingface.co/docs/hub/models-widgets-examples)
* AND this example was cached in API Inference server

#### Steps:
- [x] Implement api inference changes @Narsil @OlivierDehaene https://github.com/huggingface/api-inference/pull/1165
  - [x] If [X-Load-Model header is set to 0](https://github.com/huggingface/hub-docs/blob/4cb0e4dae893d905bf7a3a780afef231f897ce6f/js/src/lib/components/InferenceWidget/shared/helpers.ts#L83-L85), "API should to try and answer from cache and not do anything if not" (read more [here](https://github.com/huggingface/moon-landing/pull/3778#issuecomment-1259373401))
  - [x] If `X-Load-Model==0` but the request was not in cache, it should return some specific error so that widget can handle it graciously. Something like `Requested widget example was not in cache`
- [x] Implement widget changes @mishig25  https://github.com/huggingface/hub-docs/pull/293
   - [x] handle `Requested widget example was not in cache` error (i.e. it should not be shown as error, just do nothing) https://github.com/huggingface/hub-docs/pull/415
- [x] Implement hub changes @mishig25 https://github.com/huggingface/moon-landing/pull/3778

#### Resources: 
[internal slack discussion](https://huggingface.slack.com/archives/C016D661PAN/p1663622430632649)

cc: @julien-c @gary149 @osanseviero @Narsil @OlivierDehaene

**Comment by mishig25** [comment]
@Narsil @OlivierDehaene please ping me when api-inference changes are ready 👍 

the widget & hub changes should be almost ready now: I just need to test when api-inference is ready

**Comment by Narsil** [comment]
https://github.com/huggingface/api-inference/pull/1165

**Comment by mishig25** [comment]
completed! can be tested at: https://huggingface.co/facebook/detr-resnet-50
