### ISSUE TITLE
Tracking integration for Image Question Answering

### ISSUE THREAD

**Issue by osanseviero** [huggingface/hub-docs#38]
## Tracking integration of task -Image Question Answering

Note that you're not expected to do all of the following steps. This PR helps track all the steps required to get a new task fully supported in the Hub 🔥

- [x] Integration with Inference API. Select at least one of the following:
  - [x] Added a `transformers` `pipeline`
  - [ ] Added to Community Inference API for 3rd party library
  - [ ] Added to Community Inference API for generic
- [x] Added basic UI elements (icon, order specification, etc)
- [ ] Added a widget huggingface/hub-docs#21

Integration guide: https://hf.co/docs/hub/adding-a-task

cc @mishig25 @NielsRogge

**Comment by NielsRogge** [comment]
We do have a model already in the library (ViLT) that can do VQA pretty well! https://huggingface.co/spaces/nielsr/vilt-vqa

Should be relatively easy to add a pipeline for it. cc @Narsil

**Comment by osanseviero** [comment]
The pipeline is now here, so we can add this to the inference API + a widget for it (cc @mishig25). WDYT?

**Comment by osanseviero** [comment]
This is now fixed!
