### ISSUE TITLE
Tracking integration for Image to Text (Image Captioning, etc)

### ISSUE THREAD

**Issue by osanseviero** [huggingface/hub-docs#40]
## Tracking integration of task - Image to Text

Note that you're not expected to do all of the following steps. This issue helps track all the steps required to get a new task fully supported in the Hub 🔥

- [x] Integration with Inference API. Select at least one of the following:
  - [ ] Added a `transformers` `pipeline`
  - [x] Added to Community Inference API for 3rd party library
  - [ ] Added to Community Inference API for generic
- [x] Added basic UI elements (icon, order specification, etc)
- [x] Added a widget huggingface/hub-docs#15 

Integration guide: https://hf.co/docs/hub/adding-a-task

**Comment by osanseviero** [comment]
This already exists with models such as BLIP - see https://huggingface.co/models?pipeline_tag=image-to-text&sort=trending
