### ISSUE TITLE
Tracking integration for Zero-shot Image classification

### ISSUE THREAD

**Issue by osanseviero** [huggingface/hub-docs#41]
## Tracking integration of task - Zero-shot Image classification

Note that you're not expected to do all of the following steps. This PR helps track all the steps required to get a new task fully supported in the Hub 🔥

- [ ] Integration with Inference API. Select at least one of the following:
  - [x] Added a `transformers` `pipeline`
  - [ ] Added to Community Inference API for 3rd party library
  - [ ] Added to Community Inference API for generic
- [x] Added basic UI elements (icon, order specification, etc)
- [x] Added a widget [huggingface/hub-docs#14](https://github.com/huggingface/hub-docs/commit/495282b0c359896d721d9b2a2d61c3b17e2e9c5d)

Integration guide: https://hf.co/docs/hub/adding-a-task
