### ISSUE TITLE
Tracking integration for Object Detection

### ISSUE THREAD

**Issue by osanseviero** [huggingface/hub-docs#44]
## Tracking integration of task - Object Detection

Note that you're not expected to do all of the following steps. This PR helps track all the steps required to get a new task fully supported in the Hub 🔥

- [x] Integration with Inference API. Select at least one of the following:
  - [x] Added a `transformers` `pipeline` https://github.com/huggingface/transformers/blob/master/src/transformers/pipelines/object_detection.py
  - [ ] Added to Community Inference API for 3rd party library
  - [ ] Added to Community Inference API for generic
- [x] Added basic UI elements (icon, order specification, etc)
- [x] Added a widget https://github.com/huggingface/huggingface_hub/pull/247

Integration guide: https://hf.co/docs/hub/adding-a-task

**Comment by osanseviero** [comment]
This is now shipped :fire:
