### ISSUE TITLE
Feature Request: Can you add object tracking task?

### ISSUE THREAD

**Issue by kadirnar** [huggingface/hub-docs#630]

**Comment by merveenoyan** [comment]
Wanted to open the discussion from the discord, @osanseviero what is required for us to have a separate pipeline/task for object tracking in videos? Pinging @sgugger too!

**Comment by sgugger** [comment]
To have a pipeline in Transformers, we'd need pretrained models that do this. I don't think that is the case right now.

**Comment by kadirnar** [comment]
> To have a pipeline in Transformers, we'd need pretrained models that do this. I don't think that is the case right now.

Models:
- https://huggingface.co/kadirnar/osnet_x0_5_imagenet
- https://huggingface.co/kadirnar/osnet_x0_25_imagenet
- https://huggingface.co/kadirnar/osnet_x1_0_imagenet

Supported tracking algorithms:
- [X] [Sort](https://github.com/abewley/sort)
- [X] [StrongSort](https://github.com/dyhBUPT/StrongSORT)
- [X] [ByteTrack](https://github.com/ifzhang/ByteTrack)
- [X] [OcSort](https://github.com/noahcao/OC_SORT)
- [X] [Norfair](https://github.com/tryolabs/norfair/)

Demo: 
https://huggingface.co/spaces/kadirnar/torchyolo

**Comment by osanseviero** [comment]
Hey all! Let me copy-paste the template for tracking new tasks

Note that you're not expected to do all of the following steps. This helps track all the steps required to get a new task fully supported in the Hub 🔥

- [ ] Integration with Inference API. Select at least one of the following:
  - [ ] Added a `transformers` `pipeline`
  - [ ] Added to Community Inference API for 3rd party library
  - [ ] Added to Community Inference API for generic
- [ ] Added basic UI elements (icon, order specification, etc)
- [ ] Added a widget

Integration guide: https://hf.co/docs/hub/models-tasks

**Comment by merveenoyan** [comment]
@osanseviero @sgugger I was thinking more for whether there should be a separate task for this or if this could be covered under object detection as is in our ecosystem, that's why I asked above question 🙂

**Comment by osanseviero** [comment]
I think it's different, as one task operates with video as inputs (so temporal information) while the other just operates with static input images.
