### ISSUE TITLE
Types restructuring

### ISSUE THREAD

**Issue by osanseviero** [huggingface/hub-docs#83]
I will be adding a couple of notes to track here

- [x] Change to a structure that will be easier to use/scale with granular types #84
- [x] Figure out a way to skip some types to show in datasets or models (just an extra field for this, but separate PR for cleanness) #86
- [ ] Move file to better file location
- [x] Incorporate input from datasets so we're aligned (subtasks in #86 #95) 
- [x] Automatically generate data for `datasets`
