### ISSUE TITLE
Tracking integration for [TASK]

### ISSUE THREAD

**Issue by Saiful52581** [huggingface/hub-docs#912]
## Tracking integration of task - **name of task**

Note that you're not expected to do all of the following steps. This PR helps track all the steps required to get a new task fully supported in the Hub 🔥

- [x] Integration with Inference API. Select at least one of the following:
  - [x] Added a `transformers` `pipeline`
  - [x] Added to Community Inference API for 3rd party library
  - [x] Added to Community Inference API for generic
- [x] Added basic UI elements (icon, order specification, etc)
- [x] Added a widget

Integration guide: https://hf.co/docs/hub/models-tasks

**Comment by osanseviero** [comment]
Hi there! Which task would you like to be added?
